Dev
BrusnikinaV/qa-automation-java pull request #8
Opened 2022-05-29 18:38 UTC by BrusnikinaV

Задание 11 + исправление

2022-05-30 09:58 UTC, g3547 requested changes

2022-05-30 09:58 UTC, g3547 commented on src/main/java/com/tcs/edu/decorator/PageDecorator.java
>      @Override
minor(не относится к текущей задаче): не проверяется валидность последнего аргумента

2022-05-30 09:58 UTC, g3547 commented on src/main/java/com/tcs/edu/service/HashMapMessageRepository.java
> +    public void addMessage(Message message){
не понял целей существования двух методов create и addMessage
create в контексте класса репозитория понимается как "создает запись в репозитории", соответственно этим и должен заниматься (получил id сообщения, записал id и сообщение в мапу вместе с сообщением, вернул id)

у тебя же сейчас метод create ничего не создает, никак не использует входящую в него переменную- сбивает с толку

2022-05-30 09:58 UTC, g3547 commented on src/main/java/com/tcs/edu/domain/Message.java
>          this.level = level;
кажется логичным добавить сюда заполнение поля id=UUID.randomUUID(). я по заданию не увидел такого сценария, при котором нам бы пригодилось иметь сообщение без id, так что лучше чтобы он заполнялся при создании

2022-05-30 09:58 UTC, g3547 commented on src/main/java/com/tcs/edu/service/MessageService.java
> +
вижу методы по поиску сообщений, но не вижу методов чтобы добавить сообщения в репозиторий

2022-05-30 09:58 UTC, g3547 commented on src/main/java/com/tcs/edu/service/MessageService.java
> +            messagesArray[j] = new Message(level, currentString);
будет проще и правильнее передавать в метод принт уже готовые сообщения, а не собирать их здесь перед печатью)
но это рефакторинг- к актуальному заданию отношения не имеет

2022-05-30 10:40 UTC, BrusnikinaV commented on src/main/java/com/tcs/edu/service/HashMapMessageRepository.java
> +    public void addMessage(Message message){
Так написано в задании. Конечно я бы объединило в методе create и генерацию id и создание записи в map.

2022-05-31 08:59 UTC, g3547 commented on src/main/java/com/tcs/edu/service/HashMapMessageRepository.java
> +    public void addMessage(Message message){
если ты про этот пункт задания

> Вместо печати реализуем сохранение: заменить интерфейс Printer на MessageRepository с операцией UUID create(Message message)

то тут не сказано, что метод должен только генерировать новый uuid. так что ничего не мешает внутри него добавить сообщение в хранилище и только потом уже вернуть uuid

2022-05-31 09:17 UTC, g3547 commented
задания я принял, но замечания все равно лучше поправить

2022-06-05 12:56 UTC, merged